[package]
name = "fomat-macros"
version = "0.1.0"
authors = ["Michał Krasnoborski <mkrdln@gmail.com>"]

description = "Alternative syntax for print/write/format-like macros with a small templating language"

documentation = "https://docs.rs/fomat-macros"
homepage = "https://github.com/krdln/fomat-macros"
repository = "https://github.com/krdln/fomat-macros"
readme = "README.md"
keywords = ["macro", "print", "template", "format", "interpolation"]
license = "MIT"

[dependencies]
